name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'

    - name: Install dependencies
      run: |
        cd server
        npm install
        cd ../client
        npm install

    - name: Run tests
      run: |
        cd server
        npm test

    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Build and push Docker images
      run: |
        # Build and push backend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-backend:latest ./server
        docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-backend:latest
        
        # Build and push frontend
        docker build -t ${{ secrets.DOCKER_USERNAME }}/fullstack-frontend:latest ./client
        docker push ${{ secrets.DOCKER_USERNAME }}/fullstack-frontend:latest

    # Optional: Deploy to VPS
    - name: Deploy to VPS
      if: github.ref == 'refs/heads/main'
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.VPS_HOST }}
        username: ${{ secrets.VPS_USERNAME }}
        key: ${{ secrets.VPS_SSH_KEY }}
        script: |
          cd /app
          docker-compose pull
          docker-compose up -d